In [20]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn import preprocessing
import sys
import matplotlib.pyplot as plt
import timeit

import time
# from time import time

import seaborn as sns
sns.set(style="darkgrid")

from sklearn.model_selection import train_test_split
import numpy.random as nr

import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import SGDClassifier, Perceptron
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.linear_model import LogisticRegression

%matplotlib inline

In [21]:
# pca = PCA(random_state= '42')
# pca.fit(num_df)
# plt.plot(pca.explained_variance_ratio_)
nr.seed = 42

In [22]:
data = pd.read_csv("dataDropped_from_162by127_to_157rowsby84columns.csv", sep=";")
#data#.head()

In [23]:
data.columns

Index(['Unnamed: 0', '1', '2', '3', '4', '5', '6', '7', '8', '15', '16', '22',
       '23', '25', '26', '28', '29', '30', '32', '33', '34', '35', '44', '45',
       '46', '47', '48', '49', '55', '60', '61', '62', '65', '66', '67', '68',
       '69', '70', '71', '72', '75', '76', '79', '82', '83', '85', '86', '87',
       '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '100',
       '101', '102', '103', '104', '105', '106', '107', '108', '110', '111',
       '112', '113', '114', '115', '117', '118', '119', '120', '121', '122',
       '123', '124', '125', '126', '127'],
      dtype='str')

In [8]:
dfexp = data[data.columns[1:]]
dfexp

,1,2,3,4,5,6,7,8,15,16,...,118,119,120,121,122,123,124,125,126,127
0,0.0,19.0,0.0,60.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,41.5,37.5,39.1,26.82,41.06,67.88,134.08,0.506,67.88,1286.000
1,1.0,22.0,0.0,56.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,100.2,96.2,97.8,41.32,41.06,82.39,206.62,0.399,82.39,1245.000
2,2.0,23.0,0.0,57.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,91.8,87.8,89.4,39.51,53.38,92.89,197.53,0.470,92.89,1168.000
3,3.0,24.0,0.0,58.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,105.3,101.3,102.9,42.38,64.05,106.44,211.92,0.502,106.44,1154.000
4,4.0,25.0,0.0,59.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,100.8,96.8,98.4,41.45,41.06,82.51,207.26,0.398,82.51,1140.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,134.0,817.0,35.0,1.0,1.0,200.0,200.0,300.0,60000.0,150.0,...,47.9,43.9,45.5,58.26,49.37,107.63,291.28,0.369,107.63,1585.000
153,135.0,819.0,35.0,2.0,1.0,200.0,200.0,300.0,60000.0,150.0,...,50.4,46.4,48.0,59.82,159.73,219.55,299.09,0.734,219.55,0.867
154,31.0,820.0,16.0,25.0,1.0,655.0,155.0,820.0,207100.0,282.6,...,30.8,26.8,28.4,98.76,291.68,390.44,493.81,0.791,390.44,1683.000
155,32.0,821.0,16.0,27.0,1.0,655.0,155.0,820.0,207100.0,282.6,...,31.4,27.4,29.0,99.73,218.76,318.49,498.65,0.639,318.49,1794.000
156,147.0,874.0,41.0,17.0,1.0,300.0,300.0,450.0,135000.0,225.0,...,20.6,16.6,18.2,85.03,243.79,328.82,425.14,0.773,328.82,0.985

In [9]:
df_Target = dfexp[dfexp['97']/2 >= dfexp['124']]
df_Target

,1,2,3,4,5,6,7,8,15,16,...,118,119,120,121,122,123,124,125,126,127
7,7.0,45.0,3.0,147.0,1.0,585.0,75.0,800.0,277821.0,420.5,...,44.5,40.5,42.1,56.88,468.65,525.53,284.40,1848.0,284.40,3118.0
8,8.0,46.0,44.0,46.0,1.0,1450.0,150.0,1450.0,830000.0,550.1,...,43.3,39.3,40.9,218.12,2002.57,2220.69,1090.62,2036.0,1090.62,3103.0
26,26.0,248.0,14.0,61.0,1.0,400.0,80.0,500.0,104000.0,250.0,...,29.0,25.0,26.6,32.21,146.18,178.39,161.04,1108.0,161.04,2074.0
27,27.0,249.0,14.0,62.0,1.0,400.0,80.0,500.0,104000.0,250.0,...,29.0,25.0,26.6,32.21,146.18,178.39,161.04,1108.0,161.04,2167.0
79,82.0,485.0,19.0,39.0,1.0,300.0,50.0,350.0,41250.0,127.7,...,23.8,19.8,21.4,11.51,48.41,59.93,57.56,1041.0,57.56,1704.0
80,80.0,490.0,20.0,117.0,1.0,1500.0,100.0,900.0,362500.0,291.7,...,24.2,20.2,21.8,64.01,1020.61,1084.63,320.07,3389.0,320.07,2500.0
92,94.0,504.0,22.0,65.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,25.0,21.0,22.6,89.07,453.60,542.66,445.33,1219.0,445.33,1518.0
93,95.0,505.0,22.0,66.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,25.0,21.0,22.6,89.07,453.60,542.66,445.33,1219.0,445.33,1545.0
96,98.0,508.0,22.0,69.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,50.0,46.0,47.6,129.26,680.39,809.65,646.29,1253.0,646.29,1827.0
97,99.0,509.0,22.0,70.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,50.0,46.0,47.6,129.26,680.39,809.65,646.29,1253.0,646.29,1917.0
98,100.0,510.0,22.0,71.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,60.0,56.0,57.6,142.19,680.39,822.58,710.95,1157.0,710.95,1871.0
124,123.0,637.0,31.0,149.0,1.0,610.0,64.0,305.0,76786.0,113.3,...,29.9,25.9,27.5,14.88,259.00,273.88,74.42,3680.0,74.42,2150.0
125,124.0,639.0,31.0,150.0,1.0,610.0,64.0,305.0,76786.0,113.3,...,45.5,41.5,43.1,18.63,259.00,277.63,93.16,2980.0,93.16,2136.0
126,125.0,640.0,31.0,151.0,1.0,610.0,64.0,305.0,76786.0,113.3,...,34.3,30.3,31.9,16.03,388.50,404.53,80.15,5047.0,80.15,2371.0
127,126.0,642.0,31.0,152.0,1.0,610.0,64.0,305.0,76786.0,113.3,...,34.3,30.3,31.9,16.03,244.05,260.08,80.15,3245.0,80.15,2021.0
130,129.0,647.0,33.0,114.0,1.0,838.0,77.0,648.0,207323.0,318.2,...,60.6,56.6,58.2,57.56,279.65,337.22,287.81,1172.0,287.81,1865.0
131,130.0,648.0,33.0,113.0,1.0,837.0,77.0,650.0,209760.0,333.1,...,60.6,56.6,58.2,57.46,417.80,475.27,287.32,1654.0,287.32,2373.0
143,144.0,712.0,40.0,14.0,1.0,500.0,90.0,700.0,165500.0,335.5,...,88.3,84.3,85.9,89.66,558.88,648.55,448.31,1447.0,448.31,1987.0
144,145.0,713.0,40.0,16.0,1.0,500.0,90.0,700.0,165500.0,335.5,...,89.3,85.3,86.9,92.16,992.33,1084.49,460.82,2353.0,460.82,2650.0
145,146.0,714.0,40.0,18.0,1.0,500.0,90.0,700.0,165500.0,335.5,...,89.2,85.2,86.8,90.50,1425.03,1515.53,452.51,3349.0,452.51,2939.0

In [10]:
df_Target.index.to_list

<bound method IndexOpsMixin.tolist of Index([  7,   8,  26,  27,  79,  80,  92,  93,  96,  97,  98, 124, 125, 126,
       127, 130, 131, 143, 144, 145],
      dtype='int64')>

In [11]:
listTargetIndex = list(df_Target.index)
listTargetIndex

[7,
 8,
 26,
 27,
 79,
 80,
 92,
 93,
 96,
 97,
 98,
 124,
 125,
 126,
 127,
 130,
 131,
 143,
 144,
 145]

In [12]:
dfexp['Target'] = 0

In [13]:
for i in listTargetIndex:
    dfexp['Target'].iloc[i] = 1
#Try using conditional indices]

In [14]:
dfexp.iloc[listTargetIndex]

,1,2,3,4,5,6,7,8,15,16,...,119,120,121,122,123,124,125,126,127,Target
7,7.0,45.0,3.0,147.0,1.0,585.0,75.0,800.0,277821.0,420.5,...,40.5,42.1,56.88,468.65,525.53,284.40,1848.0,284.40,3118.0,0
8,8.0,46.0,44.0,46.0,1.0,1450.0,150.0,1450.0,830000.0,550.1,...,39.3,40.9,218.12,2002.57,2220.69,1090.62,2036.0,1090.62,3103.0,0
26,26.0,248.0,14.0,61.0,1.0,400.0,80.0,500.0,104000.0,250.0,...,25.0,26.6,32.21,146.18,178.39,161.04,1108.0,161.04,2074.0,0
27,27.0,249.0,14.0,62.0,1.0,400.0,80.0,500.0,104000.0,250.0,...,25.0,26.6,32.21,146.18,178.39,161.04,1108.0,161.04,2167.0,0
79,82.0,485.0,19.0,39.0,1.0,300.0,50.0,350.0,41250.0,127.7,...,19.8,21.4,11.51,48.41,59.93,57.56,1041.0,57.56,1704.0,0
80,80.0,490.0,20.0,117.0,1.0,1500.0,100.0,900.0,362500.0,291.7,...,20.2,21.8,64.01,1020.61,1084.63,320.07,3389.0,320.07,2500.0,0
92,94.0,504.0,22.0,65.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,21.0,22.6,89.07,453.60,542.66,445.33,1219.0,445.33,1518.0,0
93,95.0,505.0,22.0,66.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,21.0,22.6,89.07,453.60,542.66,445.33,1219.0,445.33,1545.0,0
96,98.0,508.0,22.0,69.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,46.0,47.6,129.26,680.39,809.65,646.29,1253.0,646.29,1827.0,0
97,99.0,509.0,22.0,70.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,46.0,47.6,129.26,680.39,809.65,646.29,1253.0,646.29,1917.0,0
98,100.0,510.0,22.0,71.0,1.0,900.0,120.0,1050.0,278000.0,432.8,...,56.0,57.6,142.19,680.39,822.58,710.95,1157.0,710.95,1871.0,0
124,123.0,637.0,31.0,149.0,1.0,610.0,64.0,305.0,76786.0,113.3,...,25.9,27.5,14.88,259.00,273.88,74.42,3680.0,74.42,2150.0,0
125,124.0,639.0,31.0,150.0,1.0,610.0,64.0,305.0,76786.0,113.3,...,41.5,43.1,18.63,259.00,277.63,93.16,2980.0,93.16,2136.0,0
126,125.0,640.0,31.0,151.0,1.0,610.0,64.0,305.0,76786.0,113.3,...,30.3,31.9,16.03,388.50,404.53,80.15,5047.0,80.15,2371.0,0
127,126.0,642.0,31.0,152.0,1.0,610.0,64.0,305.0,76786.0,113.3,...,30.3,31.9,16.03,244.05,260.08,80.15,3245.0,80.15,2021.0,0
130,129.0,647.0,33.0,114.0,1.0,838.0,77.0,648.0,207323.0,318.2,...,56.6,58.2,57.56,279.65,337.22,287.81,1172.0,287.81,1865.0,0
131,130.0,648.0,33.0,113.0,1.0,837.0,77.0,650.0,209760.0,333.1,...,56.6,58.2,57.46,417.80,475.27,287.32,1654.0,287.32,2373.0,0
143,144.0,712.0,40.0,14.0,1.0,500.0,90.0,700.0,165500.0,335.5,...,84.3,85.9,89.66,558.88,648.55,448.31,1447.0,448.31,1987.0,0
144,145.0,713.0,40.0,16.0,1.0,500.0,90.0,700.0,165500.0,335.5,...,85.3,86.9,92.16,992.33,1084.49,460.82,2353.0,460.82,2650.0,0
145,146.0,714.0,40.0,18.0,1.0,500.0,90.0,700.0,165500.0,335.5,...,85.2,86.8,90.50,1425.03,1515.53,452.51,3349.0,452.51,2939.0,0

In [15]:
dfexp

,1,2,3,4,5,6,7,8,15,16,...,119,120,121,122,123,124,125,126,127,Target
0,0.0,19.0,0.0,60.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,37.5,39.1,26.82,41.06,67.88,134.08,0.506,67.88,1286.000,0
1,1.0,22.0,0.0,56.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,96.2,97.8,41.32,41.06,82.39,206.62,0.399,82.39,1245.000,0
2,2.0,23.0,0.0,57.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,87.8,89.4,39.51,53.38,92.89,197.53,0.470,92.89,1168.000,0
3,3.0,24.0,0.0,58.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,101.3,102.9,42.38,64.05,106.44,211.92,0.502,106.44,1154.000,0
4,4.0,25.0,0.0,59.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,96.8,98.4,41.45,41.06,82.51,207.26,0.398,82.51,1140.000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,134.0,817.0,35.0,1.0,1.0,200.0,200.0,300.0,60000.0,150.0,...,43.9,45.5,58.26,49.37,107.63,291.28,0.369,107.63,1585.000,0
153,135.0,819.0,35.0,2.0,1.0,200.0,200.0,300.0,60000.0,150.0,...,46.4,48.0,59.82,159.73,219.55,299.09,0.734,219.55,0.867,0
154,31.0,820.0,16.0,25.0,1.0,655.0,155.0,820.0,207100.0,282.6,...,26.8,28.4,98.76,291.68,390.44,493.81,0.791,390.44,1683.000,0
155,32.0,821.0,16.0,27.0,1.0,655.0,155.0,820.0,207100.0,282.6,...,27.4,29.0,99.73,218.76,318.49,498.65,0.639,318.49,1794.000,0
156,147.0,874.0,41.0,17.0,1.0,300.0,300.0,450.0,135000.0,225.0,...,16.6,18.2,85.03,243.79,328.82,425.14,0.773,328.82,0.985,0

In [16]:
scaler = StandardScaler()
standardized_features = scaler.fit_transform(dfexp)
standardized_features

array([[-1.72105355, -2.14908591, -1.9688346 , ..., -0.82491838,
        -0.56068325,  0.        ],
       [-1.69898876, -2.13429062, -1.9688346 , ..., -0.74361089,
        -0.64454978,  0.        ],
       [-1.67692397, -2.12935886, -1.9688346 , ..., -0.68477363,
        -0.80205522,  0.        ],
       ...,
       [-1.03704509,  1.80125534, -0.52398724, ...,  0.98256227,
         0.25139022,  0.        ],
       [-1.0149803 ,  1.8061871 , -0.52398724, ...,  0.57938694,
         0.4784435 ,  0.        ],
       [ 1.52247045,  2.06757048,  1.73358676, ...,  0.6372716 ,
        -3.1892137 ,  0.        ]], shape=(157, 85))

In [17]:
df_standard = pd.DataFrame(standardized_features)
df_standard.index = dfexp.index
df_standard.columns = dfexp.columns

In [18]:
df_standard

,1,2,3,4,5,6,7,8,15,16,...,119,120,121,122,123,124,125,126,127,Target
0,-1.721054,-2.149086,-1.968835,-0.354802,-2.057507,-1.103863,-0.786272,-0.972286,-0.982896,-0.797984,...,-0.332096,-0.332096,-0.725716,-0.498787,-0.681524,-0.725763,-0.407708,-0.824918,-0.560683,0.0
1,-1.698989,-2.134291,-1.968835,-0.444502,-2.057507,-1.103863,-0.786272,-0.972286,-0.982896,-0.797984,...,2.012806,2.012806,-0.566462,-0.498787,-0.629092,-0.566421,-0.407836,-0.743611,-0.644550,0.0
2,-1.676924,-2.129359,-1.968835,-0.422077,-2.057507,-1.103863,-0.786272,-0.972286,-0.982896,-0.797984,...,1.677249,1.677249,-0.586341,-0.448635,-0.591150,-0.586388,-0.407751,-0.684774,-0.802055,0.0
3,-1.654859,-2.124427,-1.968835,-0.399652,-2.057507,-1.103863,-0.786272,-0.972286,-0.982896,-0.797984,...,2.216537,2.216537,-0.554820,-0.405199,-0.542187,-0.554779,-0.407712,-0.608846,-0.830693,0.0
4,-1.632794,-2.119495,-1.968835,-0.377227,-2.057507,-1.103863,-0.786272,-0.972286,-0.982896,-0.797984,...,2.036774,2.036774,-0.565034,-0.498787,-0.628658,-0.565015,-0.407837,-0.742938,-0.859330,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,1.235628,1.786460,1.191769,-1.677882,0.486025,-0.841859,0.100142,-0.772621,-0.703170,-0.585147,...,-0.076434,-0.076434,-0.380409,-0.464959,-0.537887,-0.380455,-0.407872,-0.602177,0.050929,0.0
153,1.257693,1.796324,1.191769,-1.655457,0.486025,-0.841859,0.100142,-0.772621,-0.703170,-0.585147,...,0.023434,0.023434,-0.363275,-0.015704,-0.133461,-0.363300,-0.407435,0.024972,-3.189455,0.0
154,-1.037045,1.801255,-0.523987,-1.139680,0.486025,0.791178,-0.446278,1.484465,0.780059,0.641907,...,-0.759532,-0.759532,0.064405,0.521440,0.484055,0.064425,-0.407366,0.982562,0.251390,0.0
155,-1.014980,1.806187,-0.523987,-1.094830,0.486025,0.791178,-0.446278,1.484465,0.780059,0.641907,...,-0.735563,-0.735563,0.075058,0.224596,0.224061,0.075057,-0.407548,0.579387,0.478444,0.0
156,1.522470,2.067570,1.733587,-1.319081,0.486025,-0.482950,1.314409,-0.121538,0.053065,0.108888,...,-1.166993,-1.166993,-0.086393,0.326489,0.261389,-0.086417,-0.407388,0.637272,-3.189214,0.0

In [25]:
df_standard.Target.unique

<bound method Series.unique of 4     -0.38208
5     -0.38208
6     -0.38208
7     -0.38208
8     -0.38208
        ...
156   -0.38208
157   -0.38208
158   -0.38208
159   -0.38208
160   -0.38208
Name: Target, Length: 157, dtype: float64>

In [26]:
#df_standard['Target'].unique

In [27]:
df_standard['Target'].unique()

array([-0.38208036,  2.61725047])

# How well can we classify those that fail below ACI shear from those that do not?

In [19]:
dfexp[dfexp.columns[:-1]]

,1,2,3,4,5,6,7,8,15,16,...,118,119,120,121,122,123,124,125,126,127
0,0.0,19.0,0.0,60.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,41.5,37.5,39.1,26.82,41.06,67.88,134.08,0.506,67.88,1286.000
1,1.0,22.0,0.0,56.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,100.2,96.2,97.8,41.32,41.06,82.39,206.62,0.399,82.39,1245.000
2,2.0,23.0,0.0,57.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,91.8,87.8,89.4,39.51,53.38,92.89,197.53,0.470,92.89,1168.000
3,3.0,24.0,0.0,58.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,105.3,101.3,102.9,42.38,64.05,106.44,211.92,0.502,106.44,1154.000
4,4.0,25.0,0.0,59.0,0.0,127.0,127.0,254.0,32258.0,127.0,...,100.8,96.8,98.4,41.45,41.06,82.51,207.26,0.398,82.51,1140.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,134.0,817.0,35.0,1.0,1.0,200.0,200.0,300.0,60000.0,150.0,...,47.9,43.9,45.5,58.26,49.37,107.63,291.28,0.369,107.63,1585.000
153,135.0,819.0,35.0,2.0,1.0,200.0,200.0,300.0,60000.0,150.0,...,50.4,46.4,48.0,59.82,159.73,219.55,299.09,0.734,219.55,0.867
154,31.0,820.0,16.0,25.0,1.0,655.0,155.0,820.0,207100.0,282.6,...,30.8,26.8,28.4,98.76,291.68,390.44,493.81,0.791,390.44,1683.000
155,32.0,821.0,16.0,27.0,1.0,655.0,155.0,820.0,207100.0,282.6,...,31.4,27.4,29.0,99.73,218.76,318.49,498.65,0.639,318.49,1794.000
156,147.0,874.0,41.0,17.0,1.0,300.0,300.0,450.0,135000.0,225.0,...,20.6,16.6,18.2,85.03,243.79,328.82,425.14,0.773,328.82,0.985

In [49]:
scaler = StandardScaler()
standardized_features = scaler.fit_transform(dfexp[dfexp.columns[:-1]])

X=standardized_features
y= dfexp['Target']

In [53]:
#train_test_split?

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the
    proportion of the dataset to include in the train split. If
    int, represents the absolute number of train samples. If None,
    the value is automatically set to the complement of the test size.

random_state : int, RandomState instance or None, default=None
    Controls the shuffling applied to the data before applying the split.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

shuffle : bool, default=True
    Whether or not to shuffle the data before splitting. If shuffle=False
    then stratify must be None.

stratify : array-like, default=None
    If not None, data is split in a stratified fashion, using this as
    the class labels.
    Read more in the :ref:`User Guide <stratification>`.

Returns
-------
splitting : list, length=2 * len(arrays)
    List containing train-test split of inputs.

    .. versionadded:: 0.16
        If the input is sparse, the output will be a
        ``scipy.sparse.csr_matrix``. Else, output type is the same as the
        input type.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)
>>> X
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
>>> list(y)
[0, 1, 2, 3, 4]

>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)
...
>>> X_train
array([[4, 5],
       [0, 1],
       [6, 7]])
>>> y_train
[2, 0, 3]
>>> X_test
array([[2, 3],
       [8, 9]])
>>> y_test
[1, 4]

>>> train_test_split(y, shuffle=False)
[[0, 1, 2], [3, 4]]
File:      ~/anaconda3/envs/DS/lib/python3.12/site-packages/sklearn/model_selection/_split.py
Type:      function

In [55]:
start = time.time()
#heldout = [0.95, 0.90, 0.75, 0.50, 0.01] #works well for balanced dataset
heldout = [0.90, 0.75, 0.66, 0.50, 0.01]
rounds = 20

classifiers = [
    ("SGD", SGDClassifier(max_iter=100)),
    ("ASGD", SGDClassifier(average=True)),
    ("Perceptron", Perceptron()),
    ("Passive-Aggressive I", PassiveAggressiveClassifier(loss='hinge',
                                                         C=1.0, tol=1e-4)),
    ("Passive-Aggressive II", PassiveAggressiveClassifier(loss='squared_hinge',
                                                          C=1.0, tol=1e-4)),
    ("SAG", LogisticRegression(solver='sag', tol=1e-1, C=1.e4 / X.shape[0]))
]

xx = 1. - np.array(heldout)

for name, clf in classifiers:
    print("training %s" % name)
    rng = np.random.RandomState(42)
    yy = []
    for i in heldout:
        yy_ = []
        for r in range(rounds):
            X_train, X_test, y_train, y_test = \
                train_test_split(X, y, test_size=i, random_state=rng)
            clf.fit(X_train, y_train)
            y_pred = clf.predict(X_test)
            yy_.append(1 - np.mean(y_pred == np.array(y_test)))
        yy.append(np.mean(yy_))
    plt.plot(xx, yy, label=name)

plt.legend(loc="upper right")
plt.xlabel("Proportion train")
plt.ylabel("Test Error Rate")
plt.show()
end = time.time()
print(end-start, 'seconds')

SyntaxError: keyword argument repeated: test_size (812566135.py, line 26)